spring:
  application:
    name: Sri Lanka Army Shop Management System
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: 12345678

# ----------------
shop:
  profit:
    type: PERCENTAGE
    value: 0.05
  amendments:
    TAX:
    - name: VAT
      type: PERCENTAGE
      value: 0.10
  accounting:
    organization: 1
    transactions:
      SALES: SALES
      PURCHASES: PURCHASES
    cashbooks:
      CASH: CASH
# ----------------