spring:
  application:
    name: Sri Lanka Army Shop Management System
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.8.101:3306/db01
#    url: jdbc:mysql://localhost:3306/db01
    username: user-01
    password: 1234.ASdf

# ----------------
shop:
  profit:
    type: PERCENTAGE
    value: 0.05
  amendments:
    TAX: []
#    - name: VAT
#      type: PERCENTAGE
#      value: 0.0
  accounting:
    organization: welfare
    transactions:
      SALES: SALES
      PURCHASES: PURCHASES
    cashbooks:
      CASH: CASH
# ----------------